"""empty message

Revision ID: 1fbc19b4eb26
Revises: d803edf90a57
Create Date: 2024-04-19 09:57:38.314729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbc19b4eb26'
down_revision = 'd803edf90a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('clima', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.drop_column('clima')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
