"""empty message

Revision ID: 55425377f174
Revises: d8e643884611
Create Date: 2024-04-19 16:28:43.517830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55425377f174'
down_revision = 'd8e643884611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('raza', sa.String(length=80), nullable=False),
    sa.Column('altura', sa.String(length=80), nullable=False),
    sa.Column('peso', sa.String(length=80), nullable=False),
    sa.Column('sexo', sa.String(length=80), nullable=False),
    sa.Column('color_pelo', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.drop_table('personajes')
    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('clima',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.alter_column('tripulacion',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=80),
               nullable=False)
        batch_op.alter_column('armamento',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=80),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.alter_column('armamento',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('tripulacion',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=250),
               nullable=True)

    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.alter_column('clima',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    op.create_table('personajes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('raza', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('altura', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('peso', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('sexo', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('color_pelo', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='personajes_pkey'),
    sa.UniqueConstraint('nombre', name='personajes_nombre_key')
    )
    op.drop_table('people')
    # ### end Alembic commands ###
