"""empty message

Revision ID: d803edf90a57
Revises: d6cb3ec4c78b
Create Date: 2024-04-19 09:42:32.315805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd803edf90a57'
down_revision = 'd6cb3ec4c78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poblacion', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('habitable', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planeta', schema=None) as batch_op:
        batch_op.drop_column('habitable')
        batch_op.drop_column('poblacion')

    # ### end Alembic commands ###
