"""empty message

Revision ID: d897a22b69be
Revises: 1fbc19b4eb26
Create Date: 2024-04-19 10:15:44.762525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd897a22b69be'
down_revision = '1fbc19b4eb26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('raza', sa.String(length=80), nullable=False),
    sa.Column('altura', sa.String(length=80), nullable=False),
    sa.Column('peso', sa.String(length=80), nullable=False),
    sa.Column('sexo', sa.String(length=250), nullable=True),
    sa.Column('color_pelo', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personajes')
    # ### end Alembic commands ###
